spring:
  application:
    name: post-service
  profiles:
    active: default
  data:
    mongodb:
      host: 34.101.137.236
      port: 27017
      database: femi_novia_lina
      username: femi_novia_lina
      password: password
      authentication-database: femi_novia_lina
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    org:
      springframework:
        data:
          mongodb: debug

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${random.uuid}

file:
  upload-dir: ./post-service/public