spring:
  application:
    name: user-service
  kafka:
    groupId: loggingGroup
    bootstrap-servers: 172.25.238.38:9092
    consumer:
      bootstrap-servers: 172.25.238.38:9092
      group-id: loggingGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.25.238.38:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finalproject_dev
    username: finalprojectdev
    password: finalprojectdev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${random.uuid}

jwt:
  secret: secretkey
  token.validity: 3600000

file:
  upload-dir: ./user-service/public

app:
  topic: logging
