spring:
  application:
    name: user-service
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/finalproject_dev
    username: finalprojectdev
    password: finalprojectdev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:${random.uuid}

jwt:
  secret: secretkey
  token.validity: 180000
